Master new pages
allanhaywood/CS441 pull request #17
Opened 2016-10-30 21:12 UTC by reave006

My first Pull Request!  Please let me know if I'm missing any required information.  This pull request includes a basic person class (which will probably be replaced by Allans user class) modifications to the createaccount page, creation of the about page as well as the modification of the dashboard to include the required fields to use MoviesDB.

2016-10-31 00:46 UTC, joeyfreeman commented
The password validation is pretty tricky to pass. Test123@ should be valid (based on the code comments) but I'm still receiving "Incorrect Password Format". We should tell the user what the requirements are.
The Account Details window opens correctly, but we already have a page on the dashboard for that.
For the About page, the missing full names are:
Maria Milena Arcena
Diana Anguiano
Robert Carleton

2016-10-31 03:56 UTC, allanhaywood requested changes
Please add unit tests for Account manager, especially things like validating negative and positive input for username/email/password etc.

NOTE: Don't worry about adding test for code that will be removed when you switch over to using the dbmanager.

2016-10-31 03:56 UTC, allanhaywood commented on PlotTalk/PlotTalk.pro
> +                Test/testreply.h
Fix indentation.

2016-10-31 03:56 UTC, allanhaywood commented on PlotTalk/PlotTalk.pro
> +                Test/testreply.cpp
Fix indentation.

2016-10-31 03:58 UTC, allanhaywood commented
NOTE: This is quite a big review. In the future, try and keep the reviews smaller, something that still contains a functional set of changes, but isn't so large to make the review cumbersome.

For example, one review for the new pages being added, and another review for the account manager functionality.

2016-11-02 21:29 UTC, reave006 commented
The names were changed to full names, the password field has been modified to ensure that good passwords actually work (don't know why the ones I choose worked and the ones you all choose didn't--probably ghosts).   Had to move password checking into account manager and reorganize some stuff to make unit tests work, but it was done and they are added.  All tests pass.

2016-11-03 06:16 UTC, allanhaywood commented
Other than the specific inline comments, here is some general feedback.
Ideally use doxygen format comments.
Ideally use singleton.h to make a class a singleton (I know it came after you had implemented singletons, but I believe it is easier to use, and we should consolidate on one method). First ask if the class should be a singleton.
Ideally store hashes instead of plaintext passwords: http://doc.qt.io/qt-5/qcryptographichash.html

Avoid using pointers when it is not necessary (Exception for when interacting with QT and following their best practices for that, which does involve pointers).
Prefer using references instead of pointers, when that behavior is needed.
Avoid newing up objects if they are fairly small objects that will fit on the stack.

2016-11-04 02:49 UTC, reave006 commented
Merge conflicts with master have been resolved.

2016-11-04 19:38 UTC, allanhaywood requested changes
Sorry, didn't realize I had to submit reviews again.

2016-11-04 19:38 UTC, allanhaywood commented on PlotTalk/PlotTalk.pro
> +
Remove extra lines.

2016-11-04 19:38 UTC, allanhaywood commented on PlotTalk/PlotTalk.pro
> +                Test/testreply.h
Fix indentation.

2016-11-04 19:38 UTC, allanhaywood commented on PlotTalk/PlotTalk.pro
> +                Test/testreply.cpp
Fix indentation.

2016-11-04 19:38 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.cpp
> +bool AccountManager::createAccount(QString &first, QString &last, QString &Email, QString &handle, QString &password)
Is there a reason these are all being passed in as references?
If there isn't, please change them to pass by value.

2016-11-04 19:38 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.cpp
> +bool AccountManager::findPersonByHandle(QString &handleToCheck)
Is there a reason this is being passed in as references?
If there isn't, please change them to pass by value.

2016-11-04 19:38 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.cpp
> +    for (int i =0; i<peopleList.size();i++)
Fix spacing on i =0

2016-11-04 19:38 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.cpp
> +bool AccountManager::findPersonByEmail(QString &emailtoCheck)
Same comment about pass by value.

2016-11-04 19:38 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.cpp
> +int AccountManager::checkFields(QString &fName, QString &lName, QString &handle, QString &email, QString &password)
Same comment about pass by value.

Pass by reference is only needed if the function/method will be modifying the values passed in, and you want the caller to see those changes, or it is a very large in memory object, and you want to avoid copying it.

2016-11-04 19:38 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.cpp
> +    if(validEmail->validate(email,num)==2)//valid email
A lot of nesting going on here, please simplify.

2016-11-04 19:38 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.h
> +    bool createAccount(QString &first, QString &last, QString &Email, QString &handle, QString &password);//done
Same comment about pass by value. I'll stop commenting going forward, you can apply the same feedback elsewhere where it applies.

2016-11-04 19:38 UTC, allanhaywood commented on PlotTalk/Src/createacctpage.cpp
> +           case 1:
What is case 1, case 2, case 3?

At the very least add comments to what these mean, even better use an ENUM instead, and the code will be self documenting.

http://stackoverflow.com/questions/3019153/how-do-i-use-an-enum-value-on-a-switch-statement-in-c

2016-11-06 00:46 UTC, allanhaywood approved these changes

2016-11-06 04:09 UTC, merged