Episodes
allanhaywood/CS441 pull request #27
Opened 2016-11-06 17:40 UTC by Dbrantley

What I have for the TV show class. If anything else needs to be added please let me know

2016-11-06 18:14 UTC, joeyfreeman requested changes
Does not compile. Multiple syntax errors.

2016-11-06 18:16 UTC, Dbrantley commented
Alrighty will go iron those out

2016-11-06 18:16 UTC, joeyfreeman commented on PlotTalk/Src/tvshow.h
Closing } commented out, so class definition doesn't compile

2016-11-06 18:18 UTC, joeyfreeman commented on PlotTalk/Src/episode.h
> +    Episode(int inMediaID, Qstring inUserName, Qstring inText);
Constructors should be public. Only inherited classes could instantiate Episodes if set to protected.

2016-11-06 18:22 UTC, joeyfreeman commented on PlotTalk/Src/episode.cpp
> +    this->Summary=EpSummary;
Qstring should be QString, TvshowID, TvTitle and Summary are not part of Episode

2016-11-06 18:27 UTC, joeyfreeman commented on PlotTalk/Src/tvshow.h
> +    GetSeason(SeasonId);
Can't use class variable name (SeasonId) in function declaration like this

2016-11-06 18:28 UTC, Dbrantley commented on PlotTalk/Src/tvshow.h
> +    GetSeason(SeasonId);
Hmmm so got episode class mixed up with tvshow and also some syntax errors! Sorry Will repush once i fix everything

2016-11-07 20:36 UTC, allanhaywood requested changes
Please add unit tests for this new class and any changes made.

In addition, update any existing relevant tests.

2016-11-08 07:26 UTC, joeyfreeman commented on PlotTalk/Src/episode.h
> +#include<Qstring>
Qstring

2016-11-08 08:18 UTC, allanhaywood requested changes
There is a test failure. I believe we made this change on our skype call, perhaps you didn't do a git add on the changes.

onfig: Using QtTest library 5.7.0, Qt 5.7.0 (i386-little_endian-ilp32 shared (dynamic) debug build; by MSVC 2015)
PASS   : TestTvShow::initTestCase()
FAIL!  : TestTvShow::TestConstructor() Compared values are not the same
   Actual   (ShowId)       : 0
   Expected (tvShow.showId): 9434012
..\PlotTalk\Test\testtvshow.cpp(19) : failure location
PASS   : TestTvShow::cleanupTestCase()
Totals: 2 passed, 1 failed, 0 skipped, 0 blacklisted, 1ms

2016-11-08 08:18 UTC, allanhaywood commented on PlotTalk/Src/tvshow.h
> +#endif
It's good practice to label the endif here, in this case it would have // TVSHOW_H

2016-11-09 21:41 UTC, allanhaywood approved these changes

2016-11-10 01:52 UTC, joeyfreeman approved these changes
Updated from master and moved Review and Comment vectors to episode.h. Compiles and passes all tests on my machine.

2016-11-10 07:35 UTC, merged