Season Class
allanhaywood/CS441 pull request #28
Opened 2016-11-06 19:08 UTC by ErickHeyl

Added a simple season class to be extended once TvShow / Episodes is
done

2016-11-06 20:07 UTC, haleyminshell commented on PlotTalk/Src/season.cpp
> +Season::Season(QString seasonNumber,QList episdoes)
episodes is misspelled as "episdoes". Not a big deal but just noticed.

2016-11-06 20:08 UTC, haleyminshell commented on PlotTalk/Src/season.h
> +    Qlist<Episodes> episdoes;
"episdoes" -> episodes

2016-11-07 20:34 UTC, allanhaywood requested changes
Please add unit tests for this class.

2016-11-07 20:34 UTC, allanhaywood commented on PlotTalk/Src/season.cpp
> +    return this->episdoes.size();
Optional as this is more of a style thing:

this-> is only needed when the names are hidden by local method parameters.
You should be able to use:
return episodes.size();

2016-11-08 04:05 UTC, allanhaywood requested changes
Thank you for adding the tests. There are a couple more steps to do to get them to run.

Move the references to the tests in the pro file to the test section, and add references to the test in testmain.cpp.

Details can be found in this doc: https://docs.google.com/document/d/1DiG4xUtyUR_7fSkczaVVn59AJ-xZpCTzNsWXZCk96vQ/edit#heading=h.xqfezzdmgo85

2016-11-08 04:05 UTC, allanhaywood commented on PlotTalk/PlotTalk.pro
> +    Test/testseason.h
This needs to be moved into the test section.

2016-11-08 04:05 UTC, allanhaywood commented on PlotTalk/PlotTalk.pro
> +    Test/testseason.h
See: https://docs.google.com/document/d/1DiG4xUtyUR_7fSkczaVVn59AJ-xZpCTzNsWXZCk96vQ/edit#heading=h.xqfezzdmgo85
for details.

2016-11-10 07:44 UTC, allanhaywood approved these changes

2016-11-11 02:08 UTC, merged