NOT-127, NOT-141: Integrating comments / reviews to dashboard and fixed bug with GUI.
allanhaywood/CS441 pull request #44
Opened 2016-11-22 18:36 UTC by haleyminshell

Also updated date in Reaction class to be localtime and not include UTC at the end.

2016-11-22 21:15 UTC, allanhaywood requested changes
See comment regarding time in UTC.
It is important that all time is stored in UTC.
We can then choose to convert it to the users local time for display purposes only.

2016-11-22 21:15 UTC, allanhaywood commented on PlotTalk/Src/reaction.cpp
> +    dateTimePosted = utcTime.toLocalTime().toString("MM/dd/yyyy h:mm ap");
All dates stored have to be in UTC
It should only be converted to local time when displaying in the UI to the user.
This is to allow a common stored timezone (which is commonly UTC) in the database/store, which can then be converted into whatever the localtime of the user happens to be in.

2016-11-23 03:18 UTC, joeyfreeman approved these changes
Looks good!

2016-11-23 22:47 UTC, allanhaywood approved these changes

2016-11-24 00:36 UTC, merged