Adminfunction
allanhaywood/CS441 pull request #46
Opened 2016-11-23 03:36 UTC by joeyfreeman

Submitted on behalf of Josh. Adds functionality to admin page.

2016-11-23 03:41 UTC, joeyfreeman commented on PlotTalk/Src/accountmanager.cpp
> +return createAccount(first, last, Email, handle, password, false);
Why not just add the isAdmin parameter to the original createAccount method?

2016-11-24 05:10 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.cpp
> +selectEnum AccountManager::checkFieldsAndCreate(QString fName, QString lName, QString handle, QString email, QString password, bool isAdmin)
Thank You :-)

2016-11-24 05:10 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.cpp
> +    referenceTodatabaseUser=BlankMan;
pedantic: most coding standards prefer spaces around the =

2016-11-24 05:10 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.h
> +    User BlankMan;
Pedantic: More formal/informative variable names.

2016-11-24 05:19 UTC, allanhaywood commented on PlotTalk/Src/databasemanager.cpp
> +/*
Unless there are plans to re-enable commented out code in the future, it should be removed.

2016-11-24 05:19 UTC, allanhaywood commented on PlotTalk/Src/databasemanager.h
> +    QList<User> getAllUsers();
It looks like the related code is commented out, so this shouldn't be needed. In any case, please move all logic for creating the list of user objects into account manager. You should be able to use the existing methods in databasemanager (getting a list of user names, and getting each user in a loop) within account manager.

2016-11-24 05:19 UTC, allanhaywood commented on PlotTalk/Src/user.cpp
> +    userWatched=QList<EpisodeIdentifier>();
Add this to the default constructor too.

Add spaces around the =

2016-11-24 05:19 UTC, allanhaywood commented on PlotTalk/Src/user.cpp
> +bool User::HasUserWatchedThisEpisode(EpisodeIdentifier episode, int &location)//private, checks to see if an episode is in the users watched list
casing: should be hasUserWatchedThisEpisode

2016-11-24 05:21 UTC, allanhaywood requested changes
See comments.

Let me know if you have any questions.

2016-11-24 05:21 UTC, allanhaywood commented on PlotTalk/Src/user.cpp
> +    userWatched=QList<EpisodeIdentifier>();
Applies in other method names too.

2016-11-24 06:08 UTC, joeyfreeman commented on PlotTalk/Src/accountmanager.h
> +    User BlankMan;
I second this. The BlankMan variable is unnecessary. It could just be "thisGuy = User()". Also "thisGuy" isn't very descriptive - what is this guy?

2016-11-24 06:10 UTC, joeyfreeman commented on PlotTalk/Src/accountmanager.cpp
>                  user=hold;
Changing the value of user doesn't have any effect as the parameter is pass-by-value

2016-11-25 23:08 UTC, reave006 commented on PlotTalk/Src/accountmanager.cpp
> +    referenceTodatabaseUser=BlankMan;
I'm not sure why that's still there in the pull request, it's not in my local branch I'll push it shortly.  The reason I did this is because it doesn't allow me to assign referencetodatabaseUser in the constructor.  Blankman is appropriate as it is a completely "blank man" that is there just to initialize it.

2016-11-25 23:08 UTC, reave006 commented on PlotTalk/Src/accountmanager.h
> +    User BlankMan;
this is also gone in my local branch which will be pushed shortly.

2016-11-25 23:09 UTC, reave006 commented on PlotTalk/Src/databasemanager.cpp
> +/*
deleted in new push

2016-11-25 23:09 UTC, reave006 commented on PlotTalk/Src/databasemanager.h
> +    QList<User> getAllUsers();
deleted.

2016-11-25 23:11 UTC, reave006 commented on PlotTalk/Src/user.cpp
> +    userWatched=QList<EpisodeIdentifier>();
added spaces.  Added to default constructor

2016-11-25 23:16 UTC, reave006 commented on PlotTalk/Src/user.cpp
> +bool User::HasUserWatchedThisEpisode(EpisodeIdentifier episode, int &location)//private, checks to see if an episode is in the users watched list
fixed

2016-11-25 23:19 UTC, reave006 commented on PlotTalk/Src/accountmanager.cpp
>                  user=hold;
The idea was that the method would pass back the user retrived by reference.  There's really no reason to have the user passed in if it can't be passed back.  I've changed it back to reference.  This is a function that can be used in other ways, not just how it's being used now.

2016-11-26 02:11 UTC, joeyfreeman commented on PlotTalk/Src/user.cpp
> +        for (int i=0; i<episodeList.size(); i++)
Why are you iterating over the list twice here rather than adding the episode if the user has not seen it during the first pass?

2016-11-26 23:43 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.cpp
> +    referenceTodatabaseUser=BlankMan;
Non-gender specific variables would be more appropriate.
emptyUser
blankUser
defaultUser

2016-11-26 23:48 UTC, reave006 commented on PlotTalk/Src/accountmanager.cpp
> +    referenceTodatabaseUser=BlankMan;
The red indicates that it's been removed correct?  I can change it to blank user no problem.

2016-11-26 23:48 UTC, reave006 commented on PlotTalk/Src/accountmanager.h
> +    User BlankMan;
This code in red is removed as I understand it.

2016-11-26 23:51 UTC, reave006 commented on PlotTalk/Src/user.cpp
> +        for (int i=0; i<episodeList.size(); i++)
If the user has watched any of the episodes in the list I did not want the function to add up to that point.  Iterating twice ensures that the list is not added at all if the user has watched an episode in the list.

2016-11-27 03:01 UTC, allanhaywood approved these changes
Approving, up to you on what they choose to do about comments.

2016-11-27 03:01 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.cpp
> +{\
Remove \ and fix indentation

2016-11-27 03:01 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.cpp
> +        User thisUser = User(handle, first, last, Email, password, isAdmin);//add Password Hash when possibl
Fix indentation

2016-11-27 03:01 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.cpp
> +        return true;//reminant of previous code
If you are always returning true, should this be converted to a return void function?

2016-11-27 03:01 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.cpp
> +    return true;
Same as above.

2016-11-27 03:01 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.cpp
> +    return referenceTodatabaseUser;//useful for getting info into various pages without searching the database
Fix indentation of comment, it should also be on a separate line from {
Casing is off. referenceToDatabaseUser

2016-11-27 03:01 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.h
> +    User BlankMan;
BlankMan still exists in the latest push.

2016-11-27 03:01 UTC, allanhaywood commented on PlotTalk/Src/accountmanager.h
> +    User &referenceTodatabaseUser=BlankMan;
spacing. Not a blocker, but it would be good to do a pass on your code to address spacing/readability.

2016-11-27 03:01 UTC, allanhaywood commented on PlotTalk/Src/dashboard.cpp
> +        selectEnum Problems=userInfo->checkFieldsAndCreate(newFirstName,newLastName,theUser.username,newEmail,newPassword,false);
It is also good to have a space after commas.

2016-11-27 03:01 UTC, allanhaywood commented on PlotTalk/Src/user.cpp
> +    int dummy;
dummy isn't very descriptive.

2016-11-27 03:01 UTC, allanhaywood commented on PlotTalk/Src/user.cpp
> +    if(hasTheUserWatchedAnything())
This logic could be replaced with a foreach, with no check if the user has watched anything.

If the container is emtpy, the foreach won't be entered, and it will end up returning false.

2016-11-27 03:01 UTC, allanhaywood commented on PlotTalk/Src/user.cpp
> +    if(hasTheUserWatchedAnything())
Similar comment for other for loops that are getting checked for size first.

The only disadvantage is that foreach uses a copy of the object being looped on, so you can't save a useful reference.

If a reference is needed, then for auto would work.

2016-11-27 03:08 UTC, merged